# Generated by Django 4.2.5 on 2023-09-12 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=100)),
                ('noise_level', models.CharField(max_length=100)),
                ('trend_coefficients', models.JSONField()),
                ('missing_percentage', models.FloatField()),
                ('outlier_percentage', models.FloatField()),
                ('cyclic_amplitude', models.FloatField()),
                ('cyclic_frequency', models.FloatField()),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('RUNNING', 'Running'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('use_case_name', models.CharField(max_length=200)),
                ('time_series_type', models.CharField(choices=[('ADDITIVE', 'Additive'), ('MULTIPLICATIVE', 'Multiplicative')], max_length=200)),
                ('meta_data', models.JSONField()),
                ('producer_type', models.CharField(choices=[('KAFKA', 'Kafka'), ('CSV', 'CSV')], max_length=200)),
                ('process_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seasonality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amplitude', models.FloatField()),
                ('phase_shift', models.FloatField()),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=200)),
                ('frequency_multiplier', models.FloatField()),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.dataset')),
            ],
        ),
        migrations.AddField(
            model_name='dataset',
            name='simulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulator_api.simulator'),
        ),
    ]
