# Generated by Django 4.2.5 on 2023-11-12 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator_api', '0008_alter_simulator_producer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='scheduled_interval_days',
            field=models.IntegerField(null=True),
        ),
    ]
